import type { AircraftCategory } from "@/lib/types";

export interface TypeInfo {
  manufacturer: string;
  model: string;
  category: AircraftCategory;
  /** Typical passenger-cabin class, used for sorting/labels only. */
  segment?: "light" | "midsize" | "super_midsize" | "large" | "ultra_long" | "bizliner";
}

/**
 * ICAO aircraft type designator → identity + category.
 *
 * Scope is deliberate: this table covers business aviation in depth (jets,
 * VIP airliners, business turboprops) plus enough of the airline, rotorcraft,
 * military and light-GA world to *exclude* them reliably. It is the single
 * source of truth for what counts as "private / business aviation".
 */
export const TYPE_DATABASE: Record<string, TypeInfo> = {
  // ---------------------------------------------------------------- Gulfstream
  GLF2: { manufacturer: "Gulfstream", model: "Gulfstream II", category: "business_jet", segment: "large" },
  GLF3: { manufacturer: "Gulfstream", model: "Gulfstream III", category: "business_jet", segment: "large" },
  GLF4: { manufacturer: "Gulfstream", model: "Gulfstream IV / G350 / G450", category: "business_jet", segment: "large" },
  GLF5: { manufacturer: "Gulfstream", model: "Gulfstream V / G500 / G550", category: "business_jet", segment: "ultra_long" },
  GLF6: { manufacturer: "Gulfstream", model: "G650 / G650ER", category: "business_jet", segment: "ultra_long" },
  GA5C: { manufacturer: "Gulfstream", model: "G500", category: "business_jet", segment: "large" },
  GA6C: { manufacturer: "Gulfstream", model: "G600", category: "business_jet", segment: "ultra_long" },
  GA7C: { manufacturer: "Gulfstream", model: "G700", category: "business_jet", segment: "ultra_long" },
  GA8C: { manufacturer: "Gulfstream", model: "G800", category: "business_jet", segment: "ultra_long" },
  G280: { manufacturer: "Gulfstream", model: "G280", category: "business_jet", segment: "super_midsize" },
  GALX: { manufacturer: "Gulfstream", model: "G200 / Galaxy", category: "business_jet", segment: "super_midsize" },
  G150: { manufacturer: "Gulfstream", model: "G150", category: "business_jet", segment: "midsize" },
  ASTR: { manufacturer: "IAI", model: "Astra / G100", category: "business_jet", segment: "midsize" },

  // ---------------------------------------------------------------- Bombardier
  CL30: { manufacturer: "Bombardier", model: "Challenger 300", category: "business_jet", segment: "super_midsize" },
  CL35: { manufacturer: "Bombardier", model: "Challenger 350", category: "business_jet", segment: "super_midsize" },
  CL3T: { manufacturer: "Bombardier", model: "Challenger 3500", category: "business_jet", segment: "super_midsize" },
  CL60: { manufacturer: "Bombardier", model: "Challenger 600 / 604 / 605 / 650", category: "business_jet", segment: "large" },
  GLEX: { manufacturer: "Bombardier", model: "Global Express / Global 6000", category: "business_jet", segment: "ultra_long" },
  GL5T: { manufacturer: "Bombardier", model: "Global 5000 / 5500", category: "business_jet", segment: "ultra_long" },
  GL6T: { manufacturer: "Bombardier", model: "Global 6500", category: "business_jet", segment: "ultra_long" },
  GL7T: { manufacturer: "Bombardier", model: "Global 7500", category: "business_jet", segment: "ultra_long" },
  GL8T: { manufacturer: "Bombardier", model: "Global 8000", category: "business_jet", segment: "ultra_long" },
  LJ23: { manufacturer: "Learjet", model: "Learjet 23", category: "business_jet", segment: "light" },
  LJ24: { manufacturer: "Learjet", model: "Learjet 24", category: "business_jet", segment: "light" },
  LJ25: { manufacturer: "Learjet", model: "Learjet 25", category: "business_jet", segment: "light" },
  LJ28: { manufacturer: "Learjet", model: "Learjet 28", category: "business_jet", segment: "light" },
  LJ31: { manufacturer: "Learjet", model: "Learjet 31", category: "business_jet", segment: "light" },
  LJ35: { manufacturer: "Learjet", model: "Learjet 35", category: "business_jet", segment: "light" },
  LJ36: { manufacturer: "Learjet", model: "Learjet 36", category: "business_jet", segment: "light" },
  LJ40: { manufacturer: "Learjet", model: "Learjet 40", category: "business_jet", segment: "light" },
  LJ45: { manufacturer: "Learjet", model: "Learjet 45", category: "business_jet", segment: "light" },
  LJ55: { manufacturer: "Learjet", model: "Learjet 55", category: "business_jet", segment: "midsize" },
  LJ60: { manufacturer: "Learjet", model: "Learjet 60", category: "business_jet", segment: "midsize" },
  LJ70: { manufacturer: "Learjet", model: "Learjet 70", category: "business_jet", segment: "light" },
  LJ75: { manufacturer: "Learjet", model: "Learjet 75", category: "business_jet", segment: "midsize" },

  // ------------------------------------------------------------ Cessna Citation
  C500: { manufacturer: "Cessna", model: "Citation I", category: "business_jet", segment: "light" },
  C501: { manufacturer: "Cessna", model: "Citation I/SP", category: "business_jet", segment: "light" },
  C510: { manufacturer: "Cessna", model: "Citation Mustang", category: "business_jet", segment: "light" },
  C525: { manufacturer: "Cessna", model: "CitationJet / CJ1", category: "business_jet", segment: "light" },
  C25A: { manufacturer: "Cessna", model: "Citation CJ2", category: "business_jet", segment: "light" },
  C25B: { manufacturer: "Cessna", model: "Citation CJ3", category: "business_jet", segment: "light" },
  C25C: { manufacturer: "Cessna", model: "Citation CJ4", category: "business_jet", segment: "light" },
  C25M: { manufacturer: "Cessna", model: "Citation M2", category: "business_jet", segment: "light" },
  C550: { manufacturer: "Cessna", model: "Citation II / Bravo", category: "business_jet", segment: "light" },
  C551: { manufacturer: "Cessna", model: "Citation II/SP", category: "business_jet", segment: "light" },
  C560: { manufacturer: "Cessna", model: "Citation V / Ultra / Encore", category: "business_jet", segment: "midsize" },
  C56X: { manufacturer: "Cessna", model: "Citation Excel / XLS / XLS+", category: "business_jet", segment: "midsize" },
  C650: { manufacturer: "Cessna", model: "Citation III / VI / VII", category: "business_jet", segment: "midsize" },
  C680: { manufacturer: "Cessna", model: "Citation Sovereign", category: "business_jet", segment: "super_midsize" },
  C68A: { manufacturer: "Cessna", model: "Citation Sovereign+ / Latitude", category: "business_jet", segment: "super_midsize" },
  C700: { manufacturer: "Cessna", model: "Citation Longitude", category: "business_jet", segment: "super_midsize" },
  C750: { manufacturer: "Cessna", model: "Citation X / X+", category: "business_jet", segment: "super_midsize" },

  // ------------------------------------------------------------- Dassault Falcon
  FA10: { manufacturer: "Dassault", model: "Falcon 10", category: "business_jet", segment: "light" },
  FA20: { manufacturer: "Dassault", model: "Falcon 20", category: "business_jet", segment: "midsize" },
  FA50: { manufacturer: "Dassault", model: "Falcon 50", category: "business_jet", segment: "large" },
  F2TH: { manufacturer: "Dassault", model: "Falcon 2000", category: "business_jet", segment: "large" },
  F900: { manufacturer: "Dassault", model: "Falcon 900", category: "business_jet", segment: "large" },
  FA7X: { manufacturer: "Dassault", model: "Falcon 7X", category: "business_jet", segment: "ultra_long" },
  FA8X: { manufacturer: "Dassault", model: "Falcon 8X", category: "business_jet", segment: "ultra_long" },
  FA6X: { manufacturer: "Dassault", model: "Falcon 6X", category: "business_jet", segment: "ultra_long" },

  // -------------------------------------------------------------------- Embraer
  E50P: { manufacturer: "Embraer", model: "Phenom 100", category: "business_jet", segment: "light" },
  E55P: { manufacturer: "Embraer", model: "Phenom 300", category: "business_jet", segment: "light" },
  E545: { manufacturer: "Embraer", model: "Legacy 450 / Praetor 500", category: "business_jet", segment: "midsize" },
  E550: { manufacturer: "Embraer", model: "Legacy 500 / Praetor 600", category: "business_jet", segment: "super_midsize" },
  E35L: { manufacturer: "Embraer", model: "Legacy 600 / 650", category: "business_jet", segment: "large" },
  E135: { manufacturer: "Embraer", model: "ERJ-135 / Legacy", category: "business_jet", segment: "large" },
  E190: { manufacturer: "Embraer", model: "Lineage 1000 / E190", category: "bizliner", segment: "bizliner" },

  // -------------------------------------------------- Hawker / Beechcraft jets
  H25A: { manufacturer: "Hawker", model: "HS-125 / Hawker 400-600", category: "business_jet", segment: "midsize" },
  H25B: { manufacturer: "Hawker", model: "Hawker 750 / 800 / 850XP / 900XP", category: "business_jet", segment: "midsize" },
  H25C: { manufacturer: "Hawker", model: "Hawker 1000", category: "business_jet", segment: "midsize" },
  HA4T: { manufacturer: "Hawker", model: "Hawker 4000", category: "business_jet", segment: "super_midsize" },
  BE40: { manufacturer: "Beechcraft", model: "Beechjet 400 / Hawker 400XP", category: "business_jet", segment: "light" },
  PRM1: { manufacturer: "Beechcraft", model: "Premier I / IA", category: "business_jet", segment: "light" },

  // ------------------------------------------------------------- Other bizjets
  PC24: { manufacturer: "Pilatus", model: "PC-24", category: "business_jet", segment: "light" },
  HDJT: { manufacturer: "Honda", model: "HondaJet HA-420", category: "business_jet", segment: "light" },
  SF50: { manufacturer: "Cirrus", model: "Vision Jet SF50", category: "business_jet", segment: "light" },
  EA50: { manufacturer: "Eclipse", model: "Eclipse 500/550", category: "business_jet", segment: "light" },
  EA55: { manufacturer: "Eclipse", model: "Eclipse 550", category: "business_jet", segment: "light" },
  WW24: { manufacturer: "IAI", model: "Westwind", category: "business_jet", segment: "midsize" },
  MU30: { manufacturer: "Mitsubishi", model: "Diamond / Beechjet", category: "business_jet", segment: "light" },
  SBR1: { manufacturer: "Rockwell", model: "Sabreliner", category: "business_jet", segment: "midsize" },
  JCOM: { manufacturer: "Rockwell", model: "Jet Commander", category: "business_jet", segment: "midsize" },
  BE4W: { manufacturer: "Beechcraft", model: "Beechcraft 400", category: "business_jet", segment: "light" },
  T134: { manufacturer: "Tupolev", model: "Tu-134", category: "bizliner", segment: "bizliner" },

  // -------------------------------------------------- Business turboprops
  PC12: { manufacturer: "Pilatus", model: "PC-12", category: "turboprop" },
  TBM7: { manufacturer: "Daher / Socata", model: "TBM 700", category: "turboprop" },
  TBM8: { manufacturer: "Daher / Socata", model: "TBM 850", category: "turboprop" },
  TBM9: { manufacturer: "Daher", model: "TBM 900 / 910 / 930 / 940 / 960", category: "turboprop" },
  P180: { manufacturer: "Piaggio", model: "Avanti P.180", category: "turboprop" },
  BE20: { manufacturer: "Beechcraft", model: "King Air 200 / B200", category: "turboprop" },
  B350: { manufacturer: "Beechcraft", model: "King Air 350", category: "turboprop" },
  BE30: { manufacturer: "Beechcraft", model: "King Air 300 / 350", category: "turboprop" },
  BE9L: { manufacturer: "Beechcraft", model: "King Air C90", category: "turboprop" },
  BE10: { manufacturer: "Beechcraft", model: "King Air 100", category: "turboprop" },
  BE99: { manufacturer: "Beechcraft", model: "Beech 99", category: "turboprop" },
  C441: { manufacturer: "Cessna", model: "Conquest II", category: "turboprop" },
  C425: { manufacturer: "Cessna", model: "Conquest I", category: "turboprop" },
  P46T: { manufacturer: "Piper", model: "Meridian / M500 / M600", category: "turboprop" },
  PAY1: { manufacturer: "Piper", model: "Cheyenne I", category: "turboprop" },
  PAY2: { manufacturer: "Piper", model: "Cheyenne II", category: "turboprop" },
  PAY3: { manufacturer: "Piper", model: "Cheyenne III", category: "turboprop" },
  PAY4: { manufacturer: "Piper", model: "Cheyenne 400", category: "turboprop" },
  MU2: { manufacturer: "Mitsubishi", model: "MU-2", category: "turboprop" },
  EPIC: { manufacturer: "Epic", model: "E1000", category: "turboprop" },
  E1000: { manufacturer: "Epic", model: "E1000 GX", category: "turboprop" },
  SW4: { manufacturer: "Fairchild", model: "Metroliner SA227", category: "turboprop" },
  JS31: { manufacturer: "BAe", model: "Jetstream 31", category: "turboprop" },
  JS32: { manufacturer: "BAe", model: "Jetstream 32", category: "turboprop" },

  // ------------------------------------------- Utility / light GA (excluded)
  C208: { manufacturer: "Cessna", model: "Caravan 208", category: "light_ga" },
  C08T: { manufacturer: "Cessna", model: "Grand Caravan EX", category: "light_ga" },
  KODI: { manufacturer: "Daher", model: "Kodiak 100", category: "light_ga" },
  DHC6: { manufacturer: "De Havilland Canada", model: "Twin Otter", category: "light_ga" },
  C172: { manufacturer: "Cessna", model: "172 Skyhawk", category: "light_ga" },
  C152: { manufacturer: "Cessna", model: "152", category: "light_ga" },
  C182: { manufacturer: "Cessna", model: "182 Skylane", category: "light_ga" },
  C206: { manufacturer: "Cessna", model: "206 Stationair", category: "light_ga" },
  C210: { manufacturer: "Cessna", model: "210 Centurion", category: "light_ga" },
  C310: { manufacturer: "Cessna", model: "310", category: "light_ga" },
  C337: { manufacturer: "Cessna", model: "337 Skymaster", category: "light_ga" },
  C402: { manufacturer: "Cessna", model: "402", category: "light_ga" },
  C404: { manufacturer: "Cessna", model: "Titan 404", category: "light_ga" },
  C414: { manufacturer: "Cessna", model: "Chancellor 414", category: "light_ga" },
  C421: { manufacturer: "Cessna", model: "Golden Eagle 421", category: "light_ga" },
  P28A: { manufacturer: "Piper", model: "PA-28 Cherokee", category: "light_ga" },
  P28R: { manufacturer: "Piper", model: "PA-28R Arrow", category: "light_ga" },
  PA31: { manufacturer: "Piper", model: "PA-31 Navajo", category: "light_ga" },
  PA32: { manufacturer: "Piper", model: "PA-32 Saratoga", category: "light_ga" },
  PA34: { manufacturer: "Piper", model: "PA-34 Seneca", category: "light_ga" },
  PA44: { manufacturer: "Piper", model: "PA-44 Seminole", category: "light_ga" },
  PA46: { manufacturer: "Piper", model: "PA-46 Malibu", category: "light_ga" },
  SR20: { manufacturer: "Cirrus", model: "SR20", category: "light_ga" },
  SR22: { manufacturer: "Cirrus", model: "SR22", category: "light_ga" },
  S22T: { manufacturer: "Cirrus", model: "SR22T", category: "light_ga" },
  DA40: { manufacturer: "Diamond", model: "DA40", category: "light_ga" },
  DA42: { manufacturer: "Diamond", model: "DA42 Twin Star", category: "light_ga" },
  DA62: { manufacturer: "Diamond", model: "DA62", category: "light_ga" },
  BE33: { manufacturer: "Beechcraft", model: "Debonair", category: "light_ga" },
  BE35: { manufacturer: "Beechcraft", model: "Bonanza 35", category: "light_ga" },
  BE36: { manufacturer: "Beechcraft", model: "Bonanza 36", category: "light_ga" },
  BE58: { manufacturer: "Beechcraft", model: "Baron 58", category: "light_ga" },
  M20P: { manufacturer: "Mooney", model: "M20", category: "light_ga" },
  GLID: { manufacturer: "—", model: "Glider", category: "light_ga" },
  BALL: { manufacturer: "—", model: "Balloon", category: "light_ga" },
  ULAC: { manufacturer: "—", model: "Ultralight", category: "light_ga" },

  // ------------------------------------------------------------- Helicopters
  A109: { manufacturer: "Leonardo", model: "A109", category: "helicopter" },
  A119: { manufacturer: "Leonardo", model: "AW119 Koala", category: "helicopter" },
  A139: { manufacturer: "Leonardo", model: "AW139", category: "helicopter" },
  A169: { manufacturer: "Leonardo", model: "AW169", category: "helicopter" },
  A189: { manufacturer: "Leonardo", model: "AW189", category: "helicopter" },
  EC20: { manufacturer: "Airbus Helicopters", model: "EC120 Colibri", category: "helicopter" },
  EC25: { manufacturer: "Airbus Helicopters", model: "EC225", category: "helicopter" },
  EC30: { manufacturer: "Airbus Helicopters", model: "EC130 / H130", category: "helicopter" },
  EC35: { manufacturer: "Airbus Helicopters", model: "EC135 / H135", category: "helicopter" },
  EC45: { manufacturer: "Airbus Helicopters", model: "EC145 / H145", category: "helicopter" },
  EC55: { manufacturer: "Airbus Helicopters", model: "EC155", category: "helicopter" },
  H160: { manufacturer: "Airbus Helicopters", model: "H160", category: "helicopter" },
  AS50: { manufacturer: "Airbus Helicopters", model: "AS350 Écureuil", category: "helicopter" },
  AS55: { manufacturer: "Airbus Helicopters", model: "AS355", category: "helicopter" },
  AS65: { manufacturer: "Airbus Helicopters", model: "AS365 Dauphin", category: "helicopter" },
  B06: { manufacturer: "Bell", model: "206 JetRanger", category: "helicopter" },
  B06T: { manufacturer: "Bell", model: "206LT TwinRanger", category: "helicopter" },
  B407: { manufacturer: "Bell", model: "407", category: "helicopter" },
  B412: { manufacturer: "Bell", model: "412", category: "helicopter" },
  B429: { manufacturer: "Bell", model: "429", category: "helicopter" },
  B505: { manufacturer: "Bell", model: "505 Jet Ranger X", category: "helicopter" },
  R22: { manufacturer: "Robinson", model: "R22", category: "helicopter" },
  R44: { manufacturer: "Robinson", model: "R44", category: "helicopter" },
  R66: { manufacturer: "Robinson", model: "R66", category: "helicopter" },
  S76: { manufacturer: "Sikorsky", model: "S-76", category: "helicopter" },
  S92: { manufacturer: "Sikorsky", model: "S-92", category: "helicopter" },
  H500: { manufacturer: "MD Helicopters", model: "MD500", category: "helicopter" },
  EN28: { manufacturer: "Enstrom", model: "280", category: "helicopter" },

  // ------------------------------------------------- Airline types (excluded)
  A19N: { manufacturer: "Airbus", model: "A319neo", category: "airliner" },
  A20N: { manufacturer: "Airbus", model: "A320neo", category: "airliner" },
  A21N: { manufacturer: "Airbus", model: "A321neo", category: "airliner" },
  A318: { manufacturer: "Airbus", model: "A318 / ACJ318", category: "airliner" },
  A319: { manufacturer: "Airbus", model: "A319 / ACJ319", category: "airliner" },
  A320: { manufacturer: "Airbus", model: "A320 / ACJ320", category: "airliner" },
  A321: { manufacturer: "Airbus", model: "A321", category: "airliner" },
  A332: { manufacturer: "Airbus", model: "A330-200", category: "airliner" },
  A333: { manufacturer: "Airbus", model: "A330-300", category: "airliner" },
  A339: { manufacturer: "Airbus", model: "A330-900neo", category: "airliner" },
  A342: { manufacturer: "Airbus", model: "A340-200", category: "airliner" },
  A343: { manufacturer: "Airbus", model: "A340-300", category: "airliner" },
  A345: { manufacturer: "Airbus", model: "A340-500", category: "airliner" },
  A346: { manufacturer: "Airbus", model: "A340-600", category: "airliner" },
  A359: { manufacturer: "Airbus", model: "A350-900", category: "airliner" },
  A35K: { manufacturer: "Airbus", model: "A350-1000", category: "airliner" },
  A388: { manufacturer: "Airbus", model: "A380-800", category: "airliner" },
  B712: { manufacturer: "Boeing", model: "717-200", category: "airliner" },
  B733: { manufacturer: "Boeing", model: "737-300", category: "airliner" },
  B734: { manufacturer: "Boeing", model: "737-400", category: "airliner" },
  B735: { manufacturer: "Boeing", model: "737-500", category: "airliner" },
  B736: { manufacturer: "Boeing", model: "737-600", category: "airliner" },
  B737: { manufacturer: "Boeing", model: "737-700 / BBJ", category: "airliner" },
  B738: { manufacturer: "Boeing", model: "737-800 / BBJ2", category: "airliner" },
  B739: { manufacturer: "Boeing", model: "737-900 / BBJ3", category: "airliner" },
  B38M: { manufacturer: "Boeing", model: "737 MAX 8", category: "airliner" },
  B39M: { manufacturer: "Boeing", model: "737 MAX 9", category: "airliner" },
  B37M: { manufacturer: "Boeing", model: "737 MAX 7 / BBJ MAX", category: "airliner" },
  B752: { manufacturer: "Boeing", model: "757-200", category: "airliner" },
  B753: { manufacturer: "Boeing", model: "757-300", category: "airliner" },
  B762: { manufacturer: "Boeing", model: "767-200", category: "airliner" },
  B763: { manufacturer: "Boeing", model: "767-300", category: "airliner" },
  B764: { manufacturer: "Boeing", model: "767-400", category: "airliner" },
  B772: { manufacturer: "Boeing", model: "777-200", category: "airliner" },
  B77L: { manufacturer: "Boeing", model: "777-200LR", category: "airliner" },
  B77W: { manufacturer: "Boeing", model: "777-300ER", category: "airliner" },
  B788: { manufacturer: "Boeing", model: "787-8", category: "airliner" },
  B789: { manufacturer: "Boeing", model: "787-9", category: "airliner" },
  B78X: { manufacturer: "Boeing", model: "787-10", category: "airliner" },
  B741: { manufacturer: "Boeing", model: "747-100", category: "airliner" },
  B744: { manufacturer: "Boeing", model: "747-400", category: "airliner" },
  B748: { manufacturer: "Boeing", model: "747-8", category: "airliner" },
  E145: { manufacturer: "Embraer", model: "ERJ-145", category: "airliner" },
  E170: { manufacturer: "Embraer", model: "E170", category: "airliner" },
  E75L: { manufacturer: "Embraer", model: "E175", category: "airliner" },
  E195: { manufacturer: "Embraer", model: "E195", category: "airliner" },
  E290: { manufacturer: "Embraer", model: "E190-E2", category: "airliner" },
  E295: { manufacturer: "Embraer", model: "E195-E2", category: "airliner" },
  CRJ2: { manufacturer: "Bombardier", model: "CRJ-200", category: "airliner" },
  CRJ7: { manufacturer: "Bombardier", model: "CRJ-700", category: "airliner" },
  CRJ9: { manufacturer: "Bombardier", model: "CRJ-900", category: "airliner" },
  CRJX: { manufacturer: "Bombardier", model: "CRJ-1000", category: "airliner" },
  BCS1: { manufacturer: "Airbus", model: "A220-100", category: "airliner" },
  BCS3: { manufacturer: "Airbus", model: "A220-300", category: "airliner" },
  AT43: { manufacturer: "ATR", model: "ATR 42-300", category: "airliner" },
  AT45: { manufacturer: "ATR", model: "ATR 42-500", category: "airliner" },
  AT72: { manufacturer: "ATR", model: "ATR 72", category: "airliner" },
  AT75: { manufacturer: "ATR", model: "ATR 72-500", category: "airliner" },
  AT76: { manufacturer: "ATR", model: "ATR 72-600", category: "airliner" },
  DH8A: { manufacturer: "De Havilland Canada", model: "Dash 8-100", category: "airliner" },
  DH8D: { manufacturer: "De Havilland Canada", model: "Dash 8-400", category: "airliner" },
  MD11: { manufacturer: "McDonnell Douglas", model: "MD-11", category: "airliner" },
  MD82: { manufacturer: "McDonnell Douglas", model: "MD-82", category: "airliner" },
  MD83: { manufacturer: "McDonnell Douglas", model: "MD-83", category: "airliner" },
  MD88: { manufacturer: "McDonnell Douglas", model: "MD-88", category: "airliner" },
  B190: { manufacturer: "Beechcraft", model: "1900D", category: "airliner" },
  SF34: { manufacturer: "Saab", model: "340", category: "airliner" },
  SB20: { manufacturer: "Saab", model: "2000", category: "airliner" },
  F100: { manufacturer: "Fokker", model: "100", category: "airliner" },
  F70: { manufacturer: "Fokker", model: "70", category: "airliner" },
  RJ85: { manufacturer: "BAe", model: "Avro RJ85", category: "airliner" },
  B461: { manufacturer: "BAe", model: "146-100", category: "airliner" },

  // ------------------------------------------------------ Military (opt-in)
  C130: { manufacturer: "Lockheed", model: "C-130 Hercules", category: "military" },
  C30J: { manufacturer: "Lockheed", model: "C-130J Super Hercules", category: "military" },
  C17: { manufacturer: "Boeing", model: "C-17 Globemaster III", category: "military" },
  C5M: { manufacturer: "Lockheed", model: "C-5M Super Galaxy", category: "military" },
  K35R: { manufacturer: "Boeing", model: "KC-135R Stratotanker", category: "military" },
  KC46: { manufacturer: "Boeing", model: "KC-46 Pegasus", category: "military" },
  A400: { manufacturer: "Airbus", model: "A400M Atlas", category: "military" },
  E3TF: { manufacturer: "Boeing", model: "E-3 Sentry", category: "military" },
  P8: { manufacturer: "Boeing", model: "P-8 Poseidon", category: "military" },
  F16: { manufacturer: "Lockheed", model: "F-16 Fighting Falcon", category: "military" },
  F15: { manufacturer: "Boeing", model: "F-15 Eagle", category: "military" },
  F18S: { manufacturer: "Boeing", model: "F/A-18 Super Hornet", category: "military" },
  F35: { manufacturer: "Lockheed", model: "F-35 Lightning II", category: "military" },
  EUFI: { manufacturer: "Eurofighter", model: "Typhoon", category: "military" },
  RFAL: { manufacturer: "Dassault", model: "Rafale", category: "military" },
  H60: { manufacturer: "Sikorsky", model: "UH-60 Black Hawk", category: "military" },
  V22: { manufacturer: "Bell Boeing", model: "V-22 Osprey", category: "military" },
  T38: { manufacturer: "Northrop", model: "T-38 Talon", category: "military" },
  T6: { manufacturer: "Beechcraft", model: "T-6 Texan II", category: "military" },
  U2: { manufacturer: "Lockheed", model: "U-2", category: "military" },
  GLF5T: { manufacturer: "Gulfstream", model: "C-37B", category: "military" },
};

/**
 * Airliner types that also exist as VIP / head-of-state / corporate shuttles
 * (ACJ, BBJ, Lineage, converted widebodies). A type in this set is promoted to
 * `bizliner` only when other signals agree — see `classifier.ts`.
 */
export const BIZLINER_CAPABLE = new Set([
  "A318", "A319", "A320", "A321", "A19N", "A20N", "A21N", "A332", "A333",
  "A342", "A343", "A345", "A346", "A359", "B737", "B738", "B739", "B37M",
  "B38M", "B752", "B763", "B764", "B744", "B748", "B772", "B77L", "B788",
  "B789", "E190", "E135", "E145", "CRJ2", "CRJ7", "RJ85", "F70", "F100",
  "B461", "T134",
]);

/**
 * ICAO operator codes commonly seen on private-charter, fractional and
 * management flights. A callsign beginning with one of these is business
 * aviation even when the type lookup is inconclusive.
 */
export const BIZAV_OPERATOR_CALLSIGNS: Record<string, string> = {
  EJA: "NetJets Aviation (US)",
  EJM: "Executive Jet Management",
  NJE: "NetJets Europe",
  LXJ: "Flexjet",
  FJL: "Flexjet Ltd",
  JTL: "Jet Linx",
  VJT: "VistaJet",
  VJA: "Vista America",
  XOJ: "XO Jet",
  GAJ: "Gama Aviation",
  GAK: "Gama Aviation UK",
  JMN: "Jet Management",
  WUP: "Wheels Up",
  DPJ: "Delta Private Jets",
  CPT: "Corporate Air",
  TWY: "Tag Aviation",
  TAG: "TAG Aviation",
  LNX: "Luxaviation",
  GLOBEAIR: "GlobeAir",
  GAC: "GlobeAir",
  IJM: "International Jet Management",
  DCS: "DC Aviation",
  SVW: "Silver Air",
  JAS: "Jet Aviation",
  PJS: "Jet Aviation Business Jets",
  EIS: "Air Alsie",
  FXT: "Fai Rent-a-Jet",
  IFA: "Fai Aviation",
  AHO: "Air Hamburg",
  GAM: "Gestair",
  MJF: "MJet",
  ABJ: "Abelag",
  ASJ: "Air Service Liege",
  KLJ: "K5 Aviation",
  QAJ: "Qatar Executive",
  SJU: "Saudia Private",
  AUA9: "—",
  RSJ: "Royal Jet",
  ELJ: "Elit'Avia",
  SVA9: "—",
  JEF: "Jet Executive",
  PVT: "Private flight",
  EXC: "Executive Airlines",
  BJT: "Bookajet",
  VOL: "Volare Aviation",
  SPI: "Saudi Private Aviation",
  MLC: "Malinc",
  ZEU: "Zeusch Aviation",
  NVJ: "Novo Jet",
  SXS: "SunExpress",
};

/** Military callsign prefixes, used when the feed does not set a military flag. */
export const MILITARY_CALLSIGN_PREFIXES = [
  "RCH", "RRR", "CFC", "HKY", "SPAR", "PAT", "EVAC", "DUKE", "NAVY", "ARMY",
  "GAF", "IAM", "CTM", "FAF", "SVF", "MMF", "NATO", "AME", "BAF", "HAF",
  "LAGR", "TITAN", "REACH", "ASCOT",
];

export function lookupType(typeCode: string | null | undefined): TypeInfo | null {
  if (!typeCode) return null;
  return TYPE_DATABASE[typeCode.trim().toUpperCase()] ?? null;
}
